<!-- Modal -->
<div class="modal modal--abs fade" id="wp-csp-reference" tabindex="-1" role="dialog" >
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Content Security Policy Source List Reference</h4>
      </div>
      <div class="modal-body">
      	<p>All of the directives that end with -src support similar values known as a source list. Multiple source list values can be space separated with the exception of 'none' which should be the only value..</p>
      	<table class="table table-striped table-responsive 	">
        <thead>
          <tr>
            <th>Source Value</th>
            <th>Example</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><code>*</code></td>
            <td><code>img-src *</code></td>
            <td>Wildcard, allows any URL except data: blob: filesystem: schemes.</td>
          </tr>
          <tr>
            <td><code>'none'</code></td>
            <td><code>object-src 'none'</code></td>
            <td>Prevents loading resources from any source.</td>
          </tr>
          <tr>
            <td><code>'self'</code></td>
            <td><code>script-src 'self'</code></td>
            <td>Allows loading resources from the same origin (same scheme, host and port).</td>
          </tr>
          <tr>
            <td><code>data:</code></td>
            <td><code>img-src 'self' data:</code></td>
            <td>Allows loading resources via the data scheme (eg Base64 encoded images).</td>
          </tr>
          <tr>
            <td><code><em><span class="hidden-xs">domain.</span>example.com</em></code></td>
            <td><code>img-src <span class="hidden-xs">domain.</span>example.com</code></td>
            <td>Allows loading resources from the specified domain name.</td>
          </tr>
          <tr>
            <td><code><em>*.example.com</em></code></td>
            <td><code>img-src *.example.com</code></td>
            <td>Allows loading resources from the any subdomain under <code><em>example.com</em></code>.</td>
          </tr>
          <tr>
            <td><code><em>https://cdn.com</em></code></td>
            <td><code>img-src https://cdn.com</code></td>
            <td>Allows loading resources only over HTTPS matching the given domain.</td>
          </tr>
          <tr>
            <td><code>https:</code></td>
            <td><code>img-src https:</code></td>
            <td>Allows loading resources only over HTTPS on any domain.</td>
          </tr>
          <tr>
            <td><code>'unsafe-inline'</code></td>
            <td><code>script-src 'unsafe-inline'</code></td>
            <td>Allows use of inline source elements such as style attribute, onclick, or script tag bodies (depends on the context of the source it is applied to)</td>
          </tr>
          <tr>
            <td><code>'unsafe-eval'</code></td>
            <td><code>script-src 'unsafe-eval'</code></td>
            <td>Allows unsafe dynamic code evaluation such as JavaScript <code>eval()</code></td>
          </tr>
        </tbody>
      </table>

 
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
